version: '3'

services:
  php:
    image: vuesplash
    container_name: vuesplash
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_XDEBUG_PHP_IDE_CONFIG: ${DOCKER_BUILD_ARG_PHP_XDEBUG_PHP_IDE_CONFIG:-""}
        PHP_XDEBUG_REMOTE_ENABLE: ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_ENABLE:-On}
        PHP_XDEBUG_REMOTE_AUTO_START: ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_AUTO_START:-On}
        PHP_XDEBUG_REMOTE_CONNECT_BACK: ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_CONNECT_BACK:-Off}
        PHP_XDEBUG_REMOTE_HOST: ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_HOST:-docker.for.mac.localhost}
        PHP_XDEBUG_REMOTE_PORT:  ${DOCKER_BUILD_ARG_PHP_XDEBUG_REMOTE_PORT:-9001}
        PHP_XDEBUG_IDEKEY: ${DOCKER_BUILD_ARG_PHP_XDEBUG_IDEKEY:-phpstorm}
        CHANGE_UID_GID: ${DOCKER_BUILD_ARG_CHANGE_UID_GID:-false}
        CHANGE_UID_GID_BEFORE_UID: ${DOCKER_BUILD_ARG_CHANGE_UID_GID_BEFORE_UID:-""}
        CHANGE_UID_GID_BEFORE_GID: ${DOCKER_BUILD_ARG_CHANGE_UID_GID_BEFORE_GID:-""}
    volumes:
      - .:/app
      - composer-volume:/app/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.config/psysh:/root/.config/psysh
    tty: true
    stdin_open: true
    depends_on:
      - db
  php-cli:
    image: vuesplash-cli
    container_name: vuesplash-cli
    depends_on:
      - php
    build:
      context: ./
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - .:/app
      - composer-volume:/app/vendor
      - ./.config/psysh:/root/.config/psysh
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./public:/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - 8080:80
  db:
    image: mysql:5.7
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: vuesplash_local
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
  yarn:
    build:
      context: .
      dockerfile: docker/yarn/Dockerfile
    volumes:
      - .:/app
      - node-modules-volume:/app/node_modules
volumes:
  composer-volume:
  node-modules-volume:
  mysql-volume:
